### ISSUE TITLE
The endpoint you've tried to access does not exist. Check your URL.

### ISSUE THREAD

**Issue by nu1ww** [Bogardo/Mailgun#61]
I've same issue. app develop using laravel 4.2, this package installed correctly. I'm working on local environment plan to send emails via mailgun API 
Error is :
```
Mailgun \ Connection \ Exceptions \ MissingEndpoint 
The endpoint you've tried to access does not exist. Check your URL. 
```

Domain and API set in services.php  
 
```
'mailgun' => array(
		'domain' => 'sandboxe786b43f2c3447fdaf02258fae929ab8.mailgun.org',
		'secret' => 'xxxxxx2833725df29b4ad6bbaadc1d9',)
```
can you help me to sort it out ?

**Comment by Bogardo** [comment]
On what event are you receiving this error? This exception is thrown in the [mailgun-php](https://github.com/mailgun/mailgun-php) package.

**Comment by jeffersonsetiawan** [comment]
I think it's because of how to get config variable in mailgun.

here is the snippet:
$this->from = Config::get('mailgun::from'); (Line 66)

I can solve it by changing Config::get('mailgun::from') to Config::get('mailgun.from')
(Laravel 4 use . instead of ::) @nu1ww.

Notes: change all :: to . in vendor/bogardo/mailgun/src/Bogardo/Mailgun/Mailgun.php

I know it is bad practice to changing file in vendor, but It works.

**Comment by danbovey** [comment]
As far as I can tell, support for Laravel 4.2 is broken in this package because of this issue.

So I've [forked this repo](https://github.com/europeanautomation/Mailgun) and reset it back to the last commit where the package supported Laravel 4.x and changed all of the config keys to use `.` as a separator.

If @Bogardo can accept the pull request my fork into the dev branch (if I'm right in thinking that's the branch for legacy Laravel stuff). Or potentially if `::` is used on a Laravel version I don't know about, merge it into a new branch called `4.2`.

Thanks!

**Comment by Bogardo** [comment]
I'm pretty sure Laravel 4.2 uses a `::` for accessing a package configuration file.
See https://laravel.com/docs/4.2/packages#package-configuration

Or am I missing something?

**Comment by danbovey** [comment]
Ahhhh OK forgive me not understanding package config completely. As the artisan command is broken in older versions of this because it's not tagged properly (I think this is fixed in latest), I didn't know where to put it.

I've fixed it for myself now by moving the config to `app/config/packages/bogardo/mailgun/config.php` instead of `app/config/mailgun.php` as the README states - Maybe this applies to Laravel 5? If so, change the README to say move the config to the right folder if you're on Laravel 4.x.

**Comment by Bogardo** [comment]
Please make sure you are using the correct version of this package for your version of Laravel.
If you are on Laravel 4.2, use version `3.1.*` of this package.

**Comment by danbovey** [comment]
Yep using 3.1.7. It's just me and everybody else in this issue misinterpreting the new README file. So you can probably close this.
